In [10]:
import pandas as pd
import numpy as np

URL = "https://raw.github.com/datasciencedojo/datasets/master/titanic.csv"
df = pd.read_csv(URL)
df[['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp', 'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked']]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [11]:
# Q1: Muat Dataset Titanic

import pandas as pd
import numpy as np

URL = "https://raw.github.com/datasciencedojo/datasets/master/titanic.csv"
df = pd.read_csv(URL)
print(df.shape, df.columns.tolist())

# A1: dataset Titanic memiliki 891 baris dan 12 kolom.

(891, 12) ['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp', 'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked']

In [12]:
# Q2 Kolom mana yang memiliki nilai kosong (missing)?

print(df.isnull().sum())

# A2 Data set titanic memiliki 3 kolom kosong (Missing) yaitu: Age, Cabin dan Embarked

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

In [13]:
# Q3 : Berapa persen penumpang yang selamat (Survived=1)

selamat = df[df['Survived']==1]
persentase = len(selamat)/len(df)

print ("Total Penumpang :", len(df))
print("Penumpang selamat :", df['Survived'].sum())
print("Persentase selamat (%) :", persentase * 100)

# A3 Presentase penumpang yang berhasil selamat yaitu 38.38%

Total Penumpang : 891
Penumpang selamat : 342
Persentase selamat (%) : 38.38383838383838

In [15]:
# Q4: Rata-rata usia penumpang wanita kelas 1 yang selamat

wanita_kelas1_selamat = df[
    (df['Sex'] == 'female') &
    (df['Pclass'] == 1) &
    (df['Survived'] == 1)
]
({
    "Jumlah Penumpang": [len(wanita_kelas1_selamat)],
    "Rata-rata Usia": [wanita_kelas1_selamat['Age'].mean()]
})

# A4 Rata-rata usia wanita yang selamat adalah 35 tahun

{'Jumlah Penumpang': [91], 'Rata-rata Usia': [np.float64(34.9390243902439)]}

In [16]:
# Q5: Kelas penumpang mana yang tingkat keselamatan tertinggi ?

hasil = df.groupby('Pclass').agg(
        total=('PassengerId', 'count'),
        selamat=('Survived','sum'),
        persen = ('Survived','mean'),
).round(3)
print(hasil)

# A5 tingkat keselamatan tertinggi berada di kelas 1 total 136 yang selamat

        total  selamat  persen
Pclass
1         216      136   0.630
2         184       87   0.473
3         491      119   0.242

In [17]:
# Q6: Tampilan hasil groupby('Pclass')['Survived'].mean()
df.groupby('Pclass')['Survived'].mean()

Pclass
1    0.629630
2    0.472826
3    0.242363
Name: Survived, dtype: float64